/**
 * `NdjsonWriter` — the only thing in the process that writes to stdout.
 * ADR-0002 (the line grammar), ADR-0003 (the trailer fields), ADR-0004 (the
 * ownership), ADR-0006 §5 (warning deduplication), ADR-0020 §6 (absence).
 *
 * It owns `emitted`, `skipped` and `duplicates` and is the only thing that
 * increments them, so a counter cannot disagree with the decision that moved it.
 * `finish` and `error` are the only ways to end a run, they write the single
 * trailer, and a **second** call is a bug rather than a last-writer-wins.
 *
 * ## Nothing here validates output
 *
 * ADR-0002 fixed that output line shapes are TypeScript types and are not
 * re-checked on the way out, and that the prototype sample files are the
 * normative examples and the only guard against drift. Those samples are
 * generated by driving this class, so the guard is a byte comparison against
 * output this code actually produced rather than a hand-written transcription
 * that can quietly diverge.
 *
 * ## Key order is part of the artifact
 *
 * The samples are compared byte for byte, so the order the fields are written in
 * below is load-bearing and matches the spec's examples: a `summary` reads
 * `complete, emitted, skipped, duplicates, resolved, requests, reason`, and an
 * `error` leads with ADR-0001's four mandatory fields and closes with `details`.
 *
 * ## The sink is a constructor parameter, not a test hook
 *
 * ADR-0019 §5 forbids a test-only flag or environment variable of any kind. An
 * injected sink is neither — it is the same seam ADR-0019 §4 gave the clock, on
 * the same reasoning, and the production wiring passes `process.stdout.write`
 * explicitly.
 */

import { pdError, type PdError } from "../errors.ts";
import { PdFailure } from "../pipedrive/failure.ts";
import { causeOf, isRecordRejected } from "../warnings.ts";
import type { RunDiagnostics } from "./diagnostics.ts";
import type { PdWarning } from "../warnings.ts";
import type { Bound, Page } from "../pipedrive/walk.ts";
import { renderTable } from "./pretty.ts";

/** ADR-0008: `off` on a run without `--resolve`. ADR-0009 §10's `none` is a mis-citation. */
export type Resolved = "off" | "partial" | "full";

export type Sink = (line: string) => void;

export const stdoutSink: Sink = (line) => {
	process.stdout.write(line);
};

export const stderrSink: Sink = (line) => {
	process.stderr.write(line);
};

/**
 * ADR-0006 §5: distinct causes are bounded by the size of the schema and are
 * few. This is the safeguard against a pathological schema producing unbounded
 * distinct paths; the case is not expected to occur, and `skipped` keeps
 * counting past it either way.
 */
const MAX_WARNING_CAUSES = 50;

/**
 * ADR-0003: an unbounded run writes a warning to **stderr** on crossing 10,000
 * emitted records, and again on every subsequent 10,000. The run continues; the
 * locked pagination property is untouched, and stdout never learns of it.
 *
 * It counts records rather than pages, because an agent's context is consumed
 * by records and a page is a locked-away internal concept. It is **not
 * configurable** — a configurable warning threshold is a switch nobody ever
 * turns — and it is not injectable either, which would be the test-only surface
 * ADR-0019 §5 forbids. The unit test drives 20,001 records through the writer.
 */
const SIZE_WARNING_EVERY = 10_000;

export type NdjsonWriterOptions = {
	/** ADR-0009: singular — `"deal"` for `pd deals list`. */
	recordType: string;
	/** ADR-0017: mixed item-search records carry their own validated type. */
	mixedRecordTypes?: boolean;
	/** ADR-0011 §9's dispatch counter, read once when the trailer is written. */
	requests: () => number;
	resolved?: Resolved;
	/**
	 * Output names for record fields that would shadow a line key — the resource
	 * table supplies it, and it is empty for every resource but `activities`.
	 */
	rename?: Readonly<Record<string, string>>;
	/**
	 * True when the caller passed `--limit`. A bounded run gets no size warning:
	 * it already said how much output it wants, and telling it that it received
	 * what it asked for is noise. `--max-requests` is a guard rather than a bound
	 * and does not suppress the warning.
	 */
	bounded?: boolean;
	/** ADR-0002's buffered, unstable human-only output path. */
	pretty?: boolean;
	/** Output selector order; meaningful only when `pretty` is true. */
	prettyFields?: readonly string[];
	sink?: Sink;
	/**
	 * ADR-0001 sends a human one-line summary of every error to stderr beside the
	 * machine object on stdout. Both channels are written from `error()` below, so
	 * the pair cannot come apart and no caller has to remember the second half.
	 */
	stderr?: Sink;
	/** ADR-0015's sole human diagnostics writer for data commands. */
	diagnostics?: RunDiagnostics;
};

/**
 * ADR-0020 §6. A field with no value is an **absent key**; only `null` and
 * absent are absence, so `[]`, `""` and `0` are values and survive. Stripping is
 * a serialisation rule rather than a filter, which is why it lives here and not
 * in the walk: "nothing downstream re-filters" is about records, not fields.
 *
 * `custom_fields` is the protected exception (ADR-0008 §1, ADR-0020 §6): it is
 * passthrough data rather than `pd` schema, is byte-identical with and without
 * `--resolve`, and is emitted as `{}` when empty because it is a block, not a
 * value. `id` is never absent (ADR-0016 §1) and the schema never admits it as
 * `null`, so it needs no special case.
 *
 * ## The rule reaches nested blocks, and there are more than one
 *
 * ADR-0020 §7 spelled out that §6 "applies inside those objects too" for
 * `products.prices`, and claimed that block was the only nested one. Ticket
 * 07's four other resources say otherwise: a person carries `emails`, `phones`,
 * `im` and `postal_address`, an organization carries `address`, an activity
 * carries `location`, `participants` and `attendees`. §6 is a general
 * serialisation rule, so it is applied generally rather than at one named path
 * — a `label` nobody set is an absent key wherever it sits.
 *
 * Array **elements** are never dropped, only object keys: removing an element
 * would renumber its siblings and shorten a list the caller counts.
 */
/**
 * The two keys ADR-0002's line grammar owns on a `record` line. A record field
 * of the same name would shadow the discriminator a consumer dispatches on —
 * an activity's `type` is `"call"`, and `{"type":"call"}` is not a line any
 * reader of the format can classify.
 */
const RESERVED = new Set(["type", "record_type"]);

const shrink = (value: unknown): unknown => {
	if (Array.isArray(value)) return value.map(shrink);
	return value !== null && typeof value === "object"
		? withoutAbsent(value as Record<string, unknown>)
		: value;
};

const withoutAbsent = (
	record: Record<string, unknown>,
): Record<string, unknown> => {
	const out: Record<string, unknown> = {};
	for (const [key, value] of Object.entries(record)) {
		if (value === null || value === undefined) continue;
		out[key] = shrink(value);
	}
	return out;
};

/**
 * The two ways a record can lose a field on the way out, as a value rather than
 * a throw: the caller writes the trailer before it raises, so the counters on
 * it are the true ones (ADR-0025 §1).
 */
const shadowed = (
	record: Record<string, unknown>,
	rename: Readonly<Record<string, string>>,
): PdError | undefined => {
	for (const key of Object.keys(record)) {
		const name = rename[key] ?? key;
		if (RESERVED.has(name)) {
			return pdError({
				code: "internal",
				message:
					`A record field named '${name}' would shadow the line's own '${name}' ` +
					"key. This is a bug in pd: the resource needs an output rename.",
				details: { field: name },
			});
		}
		// The rename must not land on a field the record already has. Renaming
		// `type` to `activity_type` on a resource that grows its own
		// `activity_type` would overwrite it, which is the same silent loss the
		// reserved check exists to prevent, one step further along.
		if (name !== key && name in record) {
			return pdError({
				code: "internal",
				message:
					`Renaming '${key}' to '${name}' would overwrite a field the record ` +
					"already has. This is a bug in pd: the rename needs a free name.",
				details: { field: key, renamed_to: name },
			});
		}
	}
	return undefined;
};

/**
 * `rename` carries the output name of a field that would otherwise collide with
 * `RESERVED` — `type` becomes `activity_type` on an activity. The rename is in
 * place, so the field keeps its position in the record rather than moving to
 * the end. `shadowed` above has already refused anything this would lose.
 */
const present = (
	record: Record<string, unknown>,
	rename: Readonly<Record<string, string>>,
): Record<string, unknown> => {
	const out: Record<string, unknown> = {};
	for (const [key, value] of Object.entries(record)) {
		const name = rename[key] ?? key;
		if (key === "custom_fields") {
			out[name] = value ?? {};
			continue;
		}
		if (value === null || value === undefined) continue;
		out[name] = shrink(value);
	}
	return out;
};

/** The four counters and the two run facts that ride on every trailer. */
export type TrailerCounters = {
	emitted: number;
	skipped: number;
	duplicates: number;
	resolved: Resolved;
	requests: number;
};

export const ZERO_COUNTERS: TrailerCounters = {
	emitted: 0,
	skipped: 0,
	duplicates: 0,
	resolved: "off",
	requests: 0,
};

/**
 * The error object without the trailer fields, for the three commands ADR-0009
 * §8 puts outside the NDJSON grammar — `pd auth status`, `pd cache info` and
 * `pd cache clear`. None of them is a record stream, so there is nothing for
 * `complete`, `emitted` or `requests` to say about one.
 */
const bareErrorLine = (error: PdError): Record<string, unknown> => ({
	type: "error",
	...error,
});

/**
 * Writes that error on both channels and hands back the run's exit code —
 * ADR-0001 puts the machine-readable object on stdout and a one-line human
 * summary of the same error on stderr, and the pair cannot come apart because
 * one function writes both. It is `NdjsonWriter.error` for a command that has
 * no stream and therefore no counters.
 */
export const failWith = (
	error: PdError,
	sink: Sink = stdoutSink,
	stderr: Sink = stderrSink,
): number => {
	sink(`${JSON.stringify(bareErrorLine(error))}\n`);
	stderr(`pd: ${error.message}\n`);
	return error.exit_code;
};

/**
 * The `error` trailer object, built in one place because the samples are
 * compared byte for byte and key order is therefore part of the contract:
 * ADR-0001's four mandatory fields, then `retry_after_seconds` where the variant
 * has one, then ADR-0003's counters, then `details` last.
 *
 * `details` is always present, `{}` when the error carried none. A field that
 * comes and goes is a field a consumer has to test for.
 */
export const errorLine = (
	error: PdError,
	counters: TrailerCounters,
): Record<string, unknown> => ({
	type: "error",
	code: error.code,
	message: error.message,
	exit_code: error.exit_code,
	retry: error.retry,
	...(error.retry_after_seconds === undefined
		? {}
		: { retry_after_seconds: error.retry_after_seconds }),
	complete: false,
	...counters,
	details: error.details ?? {},
});

export class NdjsonWriter {
	readonly #sink: Sink;
	readonly #stderr: Sink;
	readonly #diagnostics: RunDiagnostics | undefined;
	readonly #recordType: string;
	readonly #mixedRecordTypes: boolean;
	readonly #requests: () => number;
	#resolved: Resolved;
	readonly #rename: Readonly<Record<string, string>>;
	readonly #bounded: boolean;
	readonly #pretty: boolean;
	readonly #prettyFields: readonly string[] | undefined;
	readonly #prettyRecords: Record<string, unknown>[] = [];
	readonly #causes = new Set<string>();

	#emitted = 0;
	#skipped = 0;
	#duplicates = 0;
	#finished = false;

	constructor({
		recordType,
		mixedRecordTypes = false,
		requests,
		resolved = "off",
		rename = {},
		bounded = false,
		pretty = false,
		prettyFields,
		sink = stdoutSink,
		stderr = stderrSink,
		diagnostics,
	}: NdjsonWriterOptions) {
		this.#recordType = recordType;
		this.#mixedRecordTypes = mixedRecordTypes;
		this.#requests = requests;
		this.#resolved = resolved;
		this.#rename = rename;
		this.#bounded = bounded;
		this.#pretty = pretty;
		this.#prettyFields = prettyFields;
		this.#sink = sink;
		this.#stderr = stderr;
		this.#diagnostics = diagnostics;
	}

	#line(value: unknown): void {
		this.#sink(`${JSON.stringify(value)}\n`);
	}

	/**
	 * Warnings first, then records. A page's warnings describe records that will
	 * never appear, so emitting them ahead of the page's survivors keeps the
	 * explanation next to the gap rather than after it.
	 */
	page(page: Page<Record<string, unknown>>): void {
		this.records(this.hold(page));
	}

	/**
	 * The collected path's half of `page`: the page's warnings and its duplicate
	 * count are taken now, and its records are handed back for the caller to hold.
	 * ADR-0004 requires exactly this split — `warning` lines are written as pages
	 * arrive rather than held back, so `skipped` and `duplicates` are true on an
	 * error trailer that reports `emitted: 0`. Its stated consequence is that in
	 * the collected path every `warning` line precedes every `record` line.
	 */
	hold(page: Page<Record<string, unknown>>): Record<string, unknown>[] {
		this.#refuseAfterTrailer("page");

		for (const warning of page.warnings) {
			// Only a rejected record moves `skipped`; run-level warnings such as an
			// unmatched projection selector describe no removed record.
			if (isRecordRejected(warning)) this.#skipped += 1;
			const cause = causeOf(warning);
			if (this.#causes.has(cause)) continue;
			if (this.#causes.size >= MAX_WARNING_CAUSES) continue;
			this.#causes.add(cause);
			if (this.#pretty) this.#humanWarning(warning.message);
			else this.#line({ type: "warning", ...warning });
		}

		this.#duplicates += page.duplicates;
		return page.records;
	}

	/**
	 * Writes `record` lines and moves `emitted`. The two always happen together.
	 *
	 * A field that would shadow a line key ends the run here rather than shipping
	 * an unclassifiable line (ADR-0025 §1). The **trailer is written first**, so
	 * the counters on it are the true ones: the records already on stdout are
	 * real, and a bug is precisely when a counter must not lie. The throw that
	 * follows carries `trailer_already_written`, which is the same marker
	 * `#refuseAfterTrailer` uses and which tells `cli.ts` the whole trailer —
	 * stdout line and stderr line both — is already out.
	 */
	records(records: readonly Record<string, unknown>[]): void {
		this.#refuseAfterTrailer("page");
		for (const record of records) {
			let recordType = this.#recordType;
			let body = record;
			let collision: PdError | undefined;
			if (this.#mixedRecordTypes) {
				const { record_type: ownType, ...rest } = record;
				body = rest;
				if (typeof ownType === "string" && ownType !== "") {
					recordType = ownType;
				} else {
					collision = pdError({
						code: "internal",
						message:
							"A mixed record has no record_type. This is a bug in pd's search schema.",
					});
				}
			}
			collision ??= shadowed(body, this.#rename);
			if (collision !== undefined) {
				this.error(collision);
				throw new PdFailure(
					pdError({
						code: "internal",
						message: collision.message,
						details: { ...collision.details, trailer_already_written: true },
					}),
				);
			}
			this.#emitted += 1;
			this.#diagnostics?.record();
			const output = present(body, this.#rename);
			if (this.#pretty) this.#prettyRecords.push(output);
			else {
				this.#line({
					type: "record",
					record_type: recordType,
					...output,
				});
			}
			this.#warnOnSize();
		}
	}

	/** ADR-0003's stderr size warning, on crossing each 10,000 emitted records. */
	#warnOnSize(): void {
		if (this.#bounded) return;
		if (this.#emitted % SIZE_WARNING_EVERY !== 0) return;
		// The wording does not claim the walk continues. The threshold can be met
		// by the very last record of a complete run, and a line that said "still
		// going" would then be false on the one channel a human is reading.
		const message = `${this.#emitted} records emitted so far. Pass --limit to bound the walk.`;
		if (this.#diagnostics !== undefined) this.#diagnostics.sizeWarning(message);
		else this.#stderr(`pd: ${message}\n`);
	}

	/** A `warning` that did not come from a rejected record — a cache skip, say. */
	warn(warning: PdWarning): void {
		this.#refuseAfterTrailer("warn");
		if (this.#pretty) this.#humanWarning(warning.message);
		else this.#line({ type: "warning", ...warning });
		if (!this.#pretty && warning.kind === "cache_entry_skipped") {
			this.#diagnostics?.anomaly(warning.message);
		}
	}

	#humanWarning(message: string): void {
		if (this.#diagnostics !== undefined) this.#diagnostics.warning(message);
		else this.#stderr(`pd: ${message}\n`);
	}

	/** A permanent human diagnostic; silent in machine mode. */
	anomaly(message: string): void {
		this.#refuseAfterTrailer("anomaly");
		this.#diagnostics?.anomaly(message);
	}

	/** ADR-0008: an ancillary resolver failed after the writer was constructed. */
	resolutionPartial(): void {
		if (this.#resolved === "full") this.#resolved = "partial";
	}

	/**
	 * The `summary` trailer. `bound` is `null` for a run that fetched everything
	 * and `"limit"` for one the caller bounded; ADR-0003 keeps `reason` off every
	 * other trailer, because every guard stop is an `error` instead.
	 */
	finish(bound: Bound | null): number {
		this.#refuseAfterTrailer("finish");
		this.#finished = true;
		if (this.#pretty) {
			this.#diagnostics?.finish();
			this.#sink(
				renderTable(
					this.#prettyRecords,
					this.#prettyFields,
					this.#resolved !== "off",
				),
			);
		} else {
			this.#line({
				type: "summary",
				complete: bound === null,
				...this.#counters(),
				...(bound === null ? {} : { reason: bound }),
			});
			this.#diagnostics?.finish();
		}
		return 0;
	}

	/**
	 * The `error` trailer, and the run's exit code. ADR-0001 puts the
	 * machine-readable object on **stdout** and a one-line human summary of the
	 * same error on stderr; both are written here, so the pair cannot come apart.
	 *
	 * `details` is always present, `{}` when the error carried none.
	 */
	error(error: PdError): number {
		this.#refuseAfterTrailer("error");
		this.#finished = true;
		if (!this.#pretty) this.#line(errorLine(error, this.#counters()));
		if (this.#diagnostics !== undefined) this.#diagnostics.error(error.message);
		else this.#stderr(`pd: ${error.message}\n`);
		if (this.#pretty && this.#prettyRecords.length > 0) {
			this.#sink(
				renderTable(
					this.#prettyRecords,
					this.#prettyFields,
					this.#resolved !== "off",
				),
			);
		}
		return error.exit_code;
	}

	#counters(): TrailerCounters {
		return {
			emitted: this.#emitted,
			skipped: this.#skipped,
			duplicates: this.#duplicates,
			resolved: this.#resolved,
			requests: this.#requests(),
		};
	}

	/**
	 * ADR-0004: the exactly-one-trailer invariant is a runtime check here rather
	 * than a type, so a hand-rolled loop that writes past the trailer fails
	 * loudly. It travels as the `PdFailure` carrier for the same reason
	 * `guardedFetch`'s refusals do: there is no `Result` channel on a void method,
	 * and the top level converts it back.
	 */
	#refuseAfterTrailer(call: string): void {
		if (!this.#finished) return;
		const error = pdError({
			code: "internal",
			message:
				`pd wrote a second trailer: ${call}() was called after the run had ` +
				"already ended. This is a bug in pd.",
			// Read by `cli.ts`, which must not answer this by writing the very
			// second trailer the refusal exists to prevent. The marker covers stderr
			// as well as stdout, so the line below is the only one a reader sees.
			details: { call, trailer_already_written: true },
		});
		if (this.#diagnostics !== undefined) this.#diagnostics.error(error.message);
		else this.#stderr(`pd: ${error.message}\n`);
		throw new PdFailure(error);
	}
}
