/**
 * `NdjsonWriter` — the only thing in the process that writes to stdout.
 * ADR-0002 (the line grammar), ADR-0003 (the trailer fields), ADR-0004 (the
 * ownership), ADR-0006 §5 (warning deduplication), ADR-0020 §6 (absence).
 *
 * It owns `emitted`, `skipped` and `duplicates` and is the only thing that
 * increments them, so a counter cannot disagree with the decision that moved it.
 * `finish` and `error` are the only ways to end a run, they write the single
 * trailer, and a **second** call is a bug rather than a last-writer-wins.
 *
 * ## Nothing here validates output
 *
 * ADR-0002 fixed that output line shapes are TypeScript types and are not
 * re-checked on the way out, and that the prototype sample files are the
 * normative examples and the only guard against drift. Those samples are
 * generated by driving this class, so the guard is a byte comparison against
 * output this code actually produced rather than a hand-written transcription
 * that can quietly diverge.
 *
 * ## Key order is part of the artifact
 *
 * The samples are compared byte for byte, so the order the fields are written in
 * below is load-bearing and matches the spec's examples: a `summary` reads
 * `complete, emitted, skipped, duplicates, resolved, requests, reason`, and an
 * `error` leads with ADR-0001's four mandatory fields and closes with `details`.
 *
 * ## The sink is a constructor parameter, not a test hook
 *
 * ADR-0019 §5 forbids a test-only flag or environment variable of any kind. An
 * injected sink is neither — it is the same seam ADR-0019 §4 gave the clock, on
 * the same reasoning, and the production wiring passes `process.stdout.write`
 * explicitly.
 */

import { pdError, type PdError } from "../errors.ts";
import { PdFailure } from "../pipedrive/failure.ts";
import { causeOf } from "../warnings.ts";
import type { PdWarning } from "../warnings.ts";
import type { Bound, Page } from "../pipedrive/walk.ts";

/** ADR-0008: `off` on a run without `--resolve`. ADR-0009 §10's `none` is a mis-citation. */
export type Resolved = "off" | "partial" | "full";

export type Sink = (line: string) => void;

export const stdoutSink: Sink = (line) => {
  process.stdout.write(line);
};

export const stderrSink: Sink = (line) => {
  process.stderr.write(line);
};

/**
 * ADR-0006 §5: distinct causes are bounded by the size of the schema and are
 * few. This is the safeguard against a pathological schema producing unbounded
 * distinct paths; the case is not expected to occur, and `skipped` keeps
 * counting past it either way.
 */
const MAX_WARNING_CAUSES = 50;

export type NdjsonWriterOptions = {
  /** ADR-0009: singular — `"deal"` for `pd deals list`. */
  recordType: string;
  /** ADR-0011 §9's dispatch counter, read once when the trailer is written. */
  requests: () => number;
  resolved?: Resolved;
  sink?: Sink;
  /**
   * ADR-0001 sends a human one-line summary of every error to stderr beside the
   * machine object on stdout. Both channels are written from `error()` below, so
   * the pair cannot come apart and no caller has to remember the second half.
   */
  stderr?: Sink;
};

/**
 * ADR-0020 §6. A field with no value is an **absent key**; only `null` and
 * absent are absence, so `[]`, `""` and `0` are values and survive. Stripping is
 * a serialisation rule rather than a filter, which is why it lives here and not
 * in the walk: "nothing downstream re-filters" is about records, not fields.
 *
 * `custom_fields` is the protected exception (ADR-0008 §1, ADR-0020 §6): it is
 * passthrough data rather than `pd` schema, is byte-identical with and without
 * `--resolve`, and is emitted as `{}` when empty because it is a block, not a
 * value. `id` is never absent (ADR-0016 §1) and the schema never admits it as
 * `null`, so it needs no special case.
 */
const present = (record: Record<string, unknown>): Record<string, unknown> => {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (key === "custom_fields") {
      out[key] = value ?? {};
      continue;
    }
    if (value === null || value === undefined) continue;
    out[key] = value;
  }
  return out;
};

/** The four counters and the two run facts that ride on every trailer. */
export type TrailerCounters = {
  emitted: number;
  skipped: number;
  duplicates: number;
  resolved: Resolved;
  requests: number;
};

export const ZERO_COUNTERS: TrailerCounters = {
  emitted: 0,
  skipped: 0,
  duplicates: 0,
  resolved: "off",
  requests: 0,
};

/**
 * The `error` trailer object, built in one place because the samples are
 * compared byte for byte and key order is therefore part of the contract:
 * ADR-0001's four mandatory fields, then `retry_after_seconds` where the variant
 * has one, then ADR-0003's counters, then `details` last.
 *
 * `details` is always present, `{}` when the error carried none. A field that
 * comes and goes is a field a consumer has to test for.
 */
export const errorLine = (
  error: PdError,
  counters: TrailerCounters,
): Record<string, unknown> => ({
  type: "error",
  code: error.code,
  message: error.message,
  exit_code: error.exit_code,
  retry: error.retry,
  ...(error.retry_after_seconds === undefined
    ? {}
    : { retry_after_seconds: error.retry_after_seconds }),
  complete: false,
  ...counters,
  details: error.details ?? {},
});

export class NdjsonWriter {
  readonly #sink: Sink;
  readonly #stderr: Sink;
  readonly #recordType: string;
  readonly #requests: () => number;
  readonly #resolved: Resolved;
  readonly #causes = new Set<string>();

  #emitted = 0;
  #skipped = 0;
  #duplicates = 0;
  #finished = false;

  constructor({
    recordType,
    requests,
    resolved = "off",
    sink = stdoutSink,
    stderr = stderrSink,
  }: NdjsonWriterOptions) {
    this.#recordType = recordType;
    this.#requests = requests;
    this.#resolved = resolved;
    this.#sink = sink;
    this.#stderr = stderr;
  }

  #line(value: unknown): void {
    this.#sink(`${JSON.stringify(value)}\n`);
  }

  /**
   * Warnings first, then records. A page's warnings describe records that will
   * never appear, so emitting them ahead of the page's survivors keeps the
   * explanation next to the gap rather than after it.
   */
  page(page: Page<Record<string, unknown>>): void {
    this.records(this.hold(page));
  }

  /**
   * The collected path's half of `page`: the page's warnings and its duplicate
   * count are taken now, and its records are handed back for the caller to hold.
   * ADR-0004 requires exactly this split — `warning` lines are written as pages
   * arrive rather than held back, so `skipped` and `duplicates` are true on an
   * error trailer that reports `emitted: 0`. Its stated consequence is that in
   * the collected path every `warning` line precedes every `record` line.
   */
  hold(page: Page<Record<string, unknown>>): Record<string, unknown>[] {
    this.#refuseAfterTrailer("page");

    for (const warning of page.warnings) {
      this.#skipped += 1;
      const cause = causeOf(warning);
      if (this.#causes.has(cause)) continue;
      if (this.#causes.size >= MAX_WARNING_CAUSES) continue;
      this.#causes.add(cause);
      this.#line({ type: "warning", ...warning });
    }

    this.#duplicates += page.duplicates;
    return page.records;
  }

  /** Writes `record` lines and moves `emitted`. The two always happen together. */
  records(records: readonly Record<string, unknown>[]): void {
    this.#refuseAfterTrailer("page");
    for (const record of records) {
      this.#emitted += 1;
      this.#line({
        type: "record",
        record_type: this.#recordType,
        ...present(record),
      });
    }
  }

  /** A `warning` that did not come from a rejected record — a cache skip, say. */
  warn(warning: PdWarning): void {
    this.#refuseAfterTrailer("warn");
    this.#line({ type: "warning", ...warning });
  }

  /**
   * The `summary` trailer. `bound` is `null` for a run that fetched everything
   * and `"limit"` for one the caller bounded; ADR-0003 keeps `reason` off every
   * other trailer, because every guard stop is an `error` instead.
   */
  finish(bound: Bound | null): number {
    this.#refuseAfterTrailer("finish");
    this.#finished = true;
    this.#line({
      type: "summary",
      complete: bound === null,
      ...this.#counters(),
      ...(bound === null ? {} : { reason: bound }),
    });
    return 0;
  }

  /**
   * The `error` trailer, and the run's exit code. ADR-0001 puts the
   * machine-readable object on **stdout** and a one-line human summary of the
   * same error on stderr; both are written here, so the pair cannot come apart.
   *
   * `details` is always present, `{}` when the error carried none.
   */
  error(error: PdError): number {
    this.#refuseAfterTrailer("error");
    this.#finished = true;
    this.#line(errorLine(error, this.#counters()));
    this.#stderr(`pd: ${error.message}\n`);
    return error.exit_code;
  }

  #counters(): TrailerCounters {
    return {
      emitted: this.#emitted,
      skipped: this.#skipped,
      duplicates: this.#duplicates,
      resolved: this.#resolved,
      requests: this.#requests(),
    };
  }

  /**
   * ADR-0004: the exactly-one-trailer invariant is a runtime check here rather
   * than a type, so a hand-rolled loop that writes past the trailer fails
   * loudly. It travels as the `PdFailure` carrier for the same reason
   * `guardedFetch`'s refusals do: there is no `Result` channel on a void method,
   * and the top level converts it back.
   */
  #refuseAfterTrailer(call: string): void {
    if (!this.#finished) return;
    throw new PdFailure(
      pdError({
        code: "internal",
        message:
          `pd wrote a second trailer: ${call}() was called after the run had ` +
          "already ended. This is a bug in pd.",
        // Read by `cli.ts`, which must not answer this by writing the very
        // second trailer the refusal exists to prevent.
        details: { call, trailer_already_written: true },
      }),
    );
  }
}
