/**
 * The live-fetch resource table — ADR-0009 §1's grammar, as data.
 *
 * Ticket 05 built `pd deals list` and said the eight remaining resources would
 * be "a table entry rather than a copy of it". This file is that table. Nothing
 * about the walk, the by-id fetch, the two validation stages, the writer or the
 * exit codes is per-resource; an entry supplies four things and nothing else —
 * its plural noun, its singular `record_type`, its record schema, and the two
 * generated operations that fetch it.
 *
 * ## Five here, five elsewhere
 *
 * ADR-0009 §2 plus ADR-0017 §2 make ten resources. `pipelines`, `stages`,
 * `users` and `fields` are the cached four and arrive with ticket 08; `items`
 * is search-only and arrives with tickets 14–15. The five below are the ones
 * that fetch live on every invocation.
 *
 * ## One record schema serves both verbs
 *
 * Pipedrive titles the by-id response differently from the list response —
 * `UpsertDealResponse` against `GetDealsResponse` — so the hoist in
 * `openapi-ts.config.ts` produces two schemas per resource. They are identical
 * on all five, and `resources.test.ts` fails the build if a regeneration ever
 * makes them disagree. Until then a caller reads one shape from `list` and
 * `get` alike, which is the contract worth having.
 */

import type { Result } from "neverthrow";

import type { PdError } from "../errors.ts";
import type { Projection } from "../output/projection.ts";
import type { Entity } from "./cached.ts";
import type { PipedriveClient } from "./client.ts";
import type { ListFilterFlag, ListFilters, SortField } from "./list-filters.ts";
import type { ObjectSchema } from "./schema.ts";
import { LIST_PAGE_SIZE, walk, type Page } from "./walk.ts";
import { single } from "./single.ts";
import {
	getActivities,
	getActivity,
	getDeal,
	getDeals,
	getOrganization,
	getOrganizations,
	getPerson,
	getPersons,
	getProduct,
	getProducts,
} from "./v2/generated/sdk.gen.ts";
import {
	zGetActivitiesItem,
	zGetDealsItem,
	zGetOrganizationsItem,
	zGetPersonsItem,
	zGetProductsItem,
} from "./v2/generated/zod.gen.ts";

/** What both verbs produce, widened to the open record the writer serialises. */
export type Pages = AsyncGenerator<
	Result<Page<Record<string, unknown>>, PdError>
>;

export type Resource = {
	/** The plural noun on the command line — ADR-0009 §5, Pipedrive's own. */
	readonly name: string;
	/** ADR-0009: singular, the `record_type` on every emitted line. */
	readonly recordType: string;
	/** The matching cached field-schema source used by ADR-0008 resolution. */
	readonly entity: Entity;
	/**
	 * Output names for record fields that would shadow a line key. Empty on
	 * every resource but `activities`, whose own `type` field would otherwise
	 * overwrite ADR-0002's line discriminator.
	 */
	readonly rename: Readonly<Record<string, string>>;
	/** Raw zod field names in schema order, used for offline projection validation. */
	readonly fields: readonly string[];
	/** Flags accepted by this resource's list operation. */
	readonly filterFlags: readonly ListFilterFlag[];
	/** The endpoint's closed `sort_by` vocabulary, validated offline. */
	readonly sortFields: readonly SortField[];
	/** `limit` is ADR-0003's `--limit`, a record count; `undefined` is everything. */
	readonly list: (
		client: PipedriveClient,
		limit?: number,
		projection?: Projection,
		filters?: ListFilters,
	) => Pages;
	readonly get: (
		client: PipedriveClient,
		id: number,
		projection?: Projection,
	) => Pages;
};

type Fetch = (client: PipedriveClient) => ReturnType<PipedriveClient["v2"]>;

type Definition<T> = {
	name: string;
	recordType: string;
	entity: Entity;
	rename?: Readonly<Record<string, string>>;
	record: ObjectSchema<T>;
	/** Whether each endpoint offers ADR-0016's subtractive custom_fields parameter. */
	pushdown: { list: boolean; get: boolean };
	filterFlags: readonly ListFilterFlag[];
	sortFields: readonly SortField[];
	/** The generated list operation, already bound to its query shape. */
	page: (
		cursor: string | undefined,
		customFields: string | undefined,
		filters: ListFilters,
	) => Fetch;
	/** The generated by-id operation, already bound to its path shape. */
	one: (id: number, customFields?: string) => Fetch;
};

/**
 * The one place the concrete record type is known. `keyOf` reads `record.id`
 * without a cast because `T` is still in scope here, and the widening to the
 * open record happens on the way out — which is what lets the table hold five
 * differently-typed resources without an `as` anywhere.
 */
const define = <T extends Record<string, unknown> & { id: number }>({
	name,
	recordType,
	entity,
	rename = {},
	record,
	pushdown,
	filterFlags,
	sortFields,
	page,
	one,
}: Definition<T>): Resource => ({
	name,
	recordType,
	entity,
	rename,
	fields: Object.keys(record.shape),
	filterFlags,
	sortFields,
	list: (client, limit, projection, filters = {}) => {
		const requested = filters.ids ?? [];
		const chunks =
			requested.length === 0
				? [undefined]
				: Array.from(
						{ length: Math.ceil(requested.length / 100) },
						(_, index) => requested.slice(index * 100, (index + 1) * 100),
					);
		const completedWarnings = (seen: ReadonlySet<string | number>) => {
			const unmatched = requested.filter((id) => !seen.has(id)).length;
			if (unmatched === 0) return [];
			return [
				{
					kind: "unmatched_ids" as const,
					resource: name,
					message:
						`${unmatched} of ${requested.length} requested ids returned no record; ` +
						"they do not exist or are not visible.",
				},
			];
		};
		const serverSorted =
			filters.sortBy !== undefined || filters.sortDirection !== undefined;
		return walk<T>({
			resource: recordType,
			record,
			keyOf: (parsed) => parsed.id,
			fetchPage: (cursor, segment) =>
				page(cursor, pushdown.list ? projection?.pushdown : undefined, {
					...filters,
					ids: chunks[segment],
				})(client),
			segments: chunks.length,
			completedWarnings,
			outputOrder: serverSorted ? [] : requested,
			...(limit === undefined ? {} : { limit }),
		});
	},
	get: (client, id, projection) =>
		single<T>({
			resource: recordType,
			record,
			id,
			fetch: () =>
				one(id, pushdown.get ? projection?.pushdown : undefined)(client),
		}),
});

/**
 * The cursor query every v2 list takes: the fixed internal page size (ADR-0003
 * §1) and, after the first page, the cursor. It is identical on all five, so it
 * is written once rather than five times with one of them subtly wrong.
 */
const listQuery = (
	cursor: string | undefined,
	customFields?: string,
): { limit: number; cursor?: string; custom_fields?: string } => ({
	limit: LIST_PAGE_SIZE,
	...(cursor === undefined ? {} : { cursor }),
	...(customFields === undefined ? {} : { custom_fields: customFields }),
});

const commonFilterQuery = (filters: ListFilters) => ({
	...(filters.ids === undefined ? {} : { ids: filters.ids.join(",") }),
	...(filters.ownerId === undefined ? {} : { owner_id: filters.ownerId }),
	...(filters.updatedSince === undefined
		? {}
		: { updated_since: filters.updatedSince }),
	...(filters.sortDirection === undefined
		? {}
		: { sort_direction: filters.sortDirection }),
	...(filters.filterId === undefined ? {} : { filter_id: filters.filterId }),
});

const STANDARD_SORT_FIELDS = ["id", "update_time", "add_time"] as const;
const ACTIVITY_SORT_FIELDS = [...STANDARD_SORT_FIELDS, "due_date"] as const;
const PRODUCT_SORT_FIELDS = ["id", "name", "add_time", "update_time"] as const;

const supportedSortBy = <T extends readonly SortField[]>(
	fields: T,
	value: SortField | undefined,
): T[number] | undefined => fields.find((field) => field === value);

const timedFilterQuery = <T extends string>(
	filters: ListFilters,
	sortBy: T | undefined,
) => ({
	...commonFilterQuery(filters),
	...(filters.updatedUntil === undefined
		? {}
		: { updated_until: filters.updatedUntil }),
	...(sortBy === undefined ? {} : { sort_by: sortBy }),
});

const standardFilterQuery = (filters: ListFilters) =>
	timedFilterQuery(
		filters,
		supportedSortBy(STANDARD_SORT_FIELDS, filters.sortBy),
	);

const activityFilterQuery = (filters: ListFilters) =>
	timedFilterQuery(
		filters,
		supportedSortBy(ACTIVITY_SORT_FIELDS, filters.sortBy),
	);

const productFilterQuery = (filters: ListFilters) => {
	const sortBy = supportedSortBy(PRODUCT_SORT_FIELDS, filters.sortBy);
	return {
		...commonFilterQuery(filters),
		...(sortBy === undefined ? {} : { sort_by: sortBy }),
	};
};

const byIdQuery = (customFields?: string): { custom_fields?: string } =>
	customFields === undefined ? {} : { custom_fields: customFields };

const RESOURCES: readonly Resource[] = [
	define({
		name: "deals",
		recordType: "deal",
		entity: "deal",
		record: zGetDealsItem,
		pushdown: { list: true, get: true },
		filterFlags: [
			"ids",
			"owner-id",
			"person-id",
			"org-id",
			"pipeline-id",
			"stage-id",
			"status",
			"updated-since",
			"updated-until",
			"sort-by",
			"sort-direction",
			"filter-id",
		],
		sortFields: STANDARD_SORT_FIELDS,
		page: (cursor, customFields, filters) => (client) =>
			client.v2(getDeals, {
				query: {
					...listQuery(cursor, customFields),
					...standardFilterQuery(filters),
					...(filters.personId === undefined
						? {}
						: { person_id: filters.personId }),
					...(filters.orgId === undefined ? {} : { org_id: filters.orgId }),
					...(filters.pipelineId === undefined
						? {}
						: { pipeline_id: filters.pipelineId }),
					...(filters.stageId === undefined
						? {}
						: { stage_id: filters.stageId }),
					...(filters.status === undefined ? {} : { status: filters.status }),
				},
			}),
		one: (id, customFields) => (client) =>
			client.v2(getDeal, { path: { id }, query: byIdQuery(customFields) }),
	}),
	define({
		name: "persons",
		recordType: "person",
		entity: "person",
		record: zGetPersonsItem,
		pushdown: { list: true, get: true },
		filterFlags: [
			"ids",
			"owner-id",
			"org-id",
			"deal-id",
			"updated-since",
			"updated-until",
			"sort-by",
			"sort-direction",
			"filter-id",
		],
		sortFields: STANDARD_SORT_FIELDS,
		page: (cursor, customFields, filters) => (client) =>
			client.v2(getPersons, {
				query: {
					...listQuery(cursor, customFields),
					...standardFilterQuery(filters),
					...(filters.orgId === undefined ? {} : { org_id: filters.orgId }),
					...(filters.dealId === undefined ? {} : { deal_id: filters.dealId }),
				},
			}),
		one: (id, customFields) => (client) =>
			client.v2(getPerson, { path: { id }, query: byIdQuery(customFields) }),
	}),
	define({
		name: "organizations",
		recordType: "organization",
		entity: "organization",
		record: zGetOrganizationsItem,
		pushdown: { list: true, get: true },
		filterFlags: [
			"ids",
			"owner-id",
			"updated-since",
			"updated-until",
			"sort-by",
			"sort-direction",
			"filter-id",
		],
		sortFields: STANDARD_SORT_FIELDS,
		page: (cursor, customFields, filters) => (client) =>
			client.v2(getOrganizations, {
				query: {
					...listQuery(cursor, customFields),
					...standardFilterQuery(filters),
				},
			}),
		one: (id, customFields) => (client) =>
			client.v2(getOrganization, {
				path: { id },
				query: byIdQuery(customFields),
			}),
	}),
	define({
		name: "activities",
		recordType: "activity",
		entity: "activity",
		// An activity's own `type` is `"call"`, `"meeting"`, `"email"`. Left alone
		// it would overwrite ADR-0002's line discriminator and emit
		// `{"type":"call", …}`, which no reader of the format can classify. The
		// field is renamed rather than the record being nested under a key: the
		// line stays flat for all ten resources, and the manifest documents the
		// name (ADR-0025 §1).
		rename: { type: "activity_type" },
		record: zGetActivitiesItem,
		pushdown: { list: false, get: false },
		filterFlags: [
			"ids",
			"owner-id",
			"person-id",
			"org-id",
			"deal-id",
			"done",
			"not-done",
			"updated-since",
			"updated-until",
			"sort-by",
			"sort-direction",
			"filter-id",
		],
		sortFields: ACTIVITY_SORT_FIELDS,
		page: (cursor, _customFields, filters) => (client) =>
			client.v2(getActivities, {
				query: {
					...listQuery(cursor),
					...activityFilterQuery(filters),
					...(filters.dealId === undefined ? {} : { deal_id: filters.dealId }),
					...(filters.personId === undefined
						? {}
						: { person_id: filters.personId }),
					...(filters.orgId === undefined ? {} : { org_id: filters.orgId }),
					...(filters.done === undefined ? {} : { done: filters.done }),
				},
			}),
		one: (id) => (client) => client.v2(getActivity, { path: { id } }),
	}),
	define({
		name: "products",
		recordType: "product",
		entity: "product",
		record: zGetProductsItem,
		pushdown: { list: true, get: false },
		filterFlags: [
			"ids",
			"owner-id",
			"updated-since",
			"sort-by",
			"sort-direction",
			"filter-id",
		],
		sortFields: PRODUCT_SORT_FIELDS,
		page: (cursor, customFields, filters) => (client) =>
			client.v2(getProducts, {
				query: {
					...listQuery(cursor, customFields),
					...productFilterQuery(filters),
				},
			}),
		one: (id) => (client) => client.v2(getProduct, { path: { id } }),
	}),
];

/** Every live resource, in the order the manifest and `--help` will list them. */
export const LIVE_RESOURCES: readonly string[] = RESOURCES.map(
	(resource) => resource.name,
);

const BY_NAME = new Map(RESOURCES.map((resource) => [resource.name, resource]));

/**
 * ADR-0009 §5: no aliases and no synonyms, so this is an exact-match lookup and
 * `people` simply is not a resource.
 */
export const resourceNamed = (name: string): Resource | undefined =>
	BY_NAME.get(name);
