/**
 * The live-fetch resource table — ADR-0009 §1's grammar, as data.
 *
 * Ticket 05 built `pd deals list` and said the eight remaining resources would
 * be "a table entry rather than a copy of it". This file is that table. Nothing
 * about the walk, the by-id fetch, the two validation stages, the writer or the
 * exit codes is per-resource; an entry supplies four things and nothing else —
 * its plural noun, its singular `record_type`, its record schema, and the two
 * generated operations that fetch it.
 *
 * ## Five here, five elsewhere
 *
 * ADR-0009 §2 plus ADR-0017 §2 make ten resources. `pipelines`, `stages`,
 * `users` and `fields` are the cached four and arrive with ticket 08; `items`
 * is search-only and arrives with tickets 14–15. The five below are the ones
 * that fetch live on every invocation.
 *
 * ## One record schema serves both verbs
 *
 * Pipedrive titles the by-id response differently from the list response —
 * `UpsertDealResponse` against `GetDealsResponse` — so the hoist in
 * `openapi-ts.config.ts` produces two schemas per resource. They are identical
 * on all five, and `resources.test.ts` fails the build if a regeneration ever
 * makes them disagree. Until then a caller reads one shape from `list` and
 * `get` alike, which is the contract worth having.
 */

import type { z } from "zod";
import type { Result } from "neverthrow";

import type { PdError } from "../errors.ts";
import type { Projection } from "../output/projection.ts";
import type { PipedriveClient } from "./client.ts";
import { LIST_PAGE_SIZE, walk, type Page } from "./walk.ts";
import { single } from "./single.ts";
import {
  getActivities,
  getActivity,
  getDeal,
  getDeals,
  getOrganization,
  getOrganizations,
  getPerson,
  getPersons,
  getProduct,
  getProducts,
} from "./v2/generated/sdk.gen.ts";
import {
  zGetActivitiesItem,
  zGetDealsItem,
  zGetOrganizationsItem,
  zGetPersonsItem,
  zGetProductsItem,
} from "./v2/generated/zod.gen.ts";

/** What both verbs produce, widened to the open record the writer serialises. */
export type Pages = AsyncGenerator<
  Result<Page<Record<string, unknown>>, PdError>
>;

export type Resource = {
  /** The plural noun on the command line — ADR-0009 §5, Pipedrive's own. */
  readonly name: string;
  /** ADR-0009: singular, the `record_type` on every emitted line. */
  readonly recordType: string;
  /**
   * Output names for record fields that would shadow a line key. Empty on
   * every resource but `activities`, whose own `type` field would otherwise
   * overwrite ADR-0002's line discriminator.
   */
  readonly rename: Readonly<Record<string, string>>;
  /** Output field names in zod/schema order, used for offline projection validation. */
  readonly fields: readonly string[];
  /** `limit` is ADR-0003's `--limit`, a record count; `undefined` is everything. */
  readonly list: (client: PipedriveClient, limit?: number, projection?: Projection) => Pages;
  readonly get: (client: PipedriveClient, id: number, projection?: Projection) => Pages;
};

type Fetch = (
  client: PipedriveClient,
) => ReturnType<PipedriveClient["v2"]>;

type Definition<T> = {
  name: string;
  recordType: string;
  rename?: Readonly<Record<string, string>>;
  record: z.ZodType<T, unknown>;
  fields: readonly string[];
  /** Whether each endpoint offers ADR-0016's subtractive custom_fields parameter. */
  pushdown: { list: boolean; get: boolean };
  /** The generated list operation, already bound to its query shape. */
  page: (cursor: string | undefined, customFields?: string) => Fetch;
  /** The generated by-id operation, already bound to its path shape. */
  one: (id: number, customFields?: string) => Fetch;
};

/**
 * The one place the concrete record type is known. `keyOf` reads `record.id`
 * without a cast because `T` is still in scope here, and the widening to the
 * open record happens on the way out — which is what lets the table hold five
 * differently-typed resources without an `as` anywhere.
 */
const define = <T extends { id: number }>({
  name,
  recordType,
  rename = {},
  record,
  fields,
  pushdown,
  page,
  one,
}: Definition<T>): Resource => ({
  name,
  recordType,
  rename,
  fields,
  list: (client, limit, projection) =>
    walk<T>({
      resource: recordType,
      record,
      keyOf: (parsed) => parsed.id,
      fetchPage: (cursor) => page(
        cursor,
        pushdown.list ? projection?.pushdown : undefined,
      )(client),
      ...(limit === undefined ? {} : { limit }),
    }),
  get: (client, id, projection) =>
    single<T>({
      resource: recordType,
      record,
      id,
      fetch: () => one(id, pushdown.get ? projection?.pushdown : undefined)(client),
    }),
});

/**
 * The cursor query every v2 list takes: the fixed internal page size (ADR-0003
 * §1) and, after the first page, the cursor. It is identical on all five, so it
 * is written once rather than five times with one of them subtly wrong.
 */
const listQuery = (
  cursor: string | undefined,
  customFields?: string,
): { limit: number; cursor?: string; custom_fields?: string } => ({
  limit: LIST_PAGE_SIZE,
  ...(cursor === undefined ? {} : { cursor }),
  ...(customFields === undefined ? {} : { custom_fields: customFields }),
});

const byIdQuery = (customFields?: string): { custom_fields?: string } =>
  customFields === undefined ? {} : { custom_fields: customFields };

const RESOURCES: readonly Resource[] = [
  define({
    name: "deals",
    recordType: "deal",
    record: zGetDealsItem,
    fields: Object.keys(zGetDealsItem.shape),
    pushdown: { list: true, get: true },
    page: (cursor, customFields) => (client) =>
      client.v2(getDeals, { query: listQuery(cursor, customFields) }),
    one: (id, customFields) => (client) =>
      client.v2(getDeal, { path: { id }, query: byIdQuery(customFields) }),
  }),
  define({
    name: "persons",
    recordType: "person",
    record: zGetPersonsItem,
    fields: Object.keys(zGetPersonsItem.shape),
    pushdown: { list: true, get: true },
    page: (cursor, customFields) => (client) =>
      client.v2(getPersons, { query: listQuery(cursor, customFields) }),
    one: (id, customFields) => (client) =>
      client.v2(getPerson, { path: { id }, query: byIdQuery(customFields) }),
  }),
  define({
    name: "organizations",
    recordType: "organization",
    record: zGetOrganizationsItem,
    fields: Object.keys(zGetOrganizationsItem.shape),
    pushdown: { list: true, get: true },
    page: (cursor, customFields) => (client) =>
      client.v2(getOrganizations, { query: listQuery(cursor, customFields) }),
    one: (id, customFields) => (client) =>
      client.v2(getOrganization, { path: { id }, query: byIdQuery(customFields) }),
  }),
  define({
    name: "activities",
    recordType: "activity",
    // An activity's own `type` is `"call"`, `"meeting"`, `"email"`. Left alone
    // it would overwrite ADR-0002's line discriminator and emit
    // `{"type":"call", …}`, which no reader of the format can classify. The
    // field is renamed rather than the record being nested under a key: the
    // line stays flat for all ten resources, and the manifest documents the
    // name (ADR-0025 §1).
    rename: { type: "activity_type" },
    record: zGetActivitiesItem,
    fields: Object.keys(zGetActivitiesItem.shape),
    pushdown: { list: false, get: false },
    page: (cursor) => (client) =>
      client.v2(getActivities, { query: listQuery(cursor) }),
    one: (id) => (client) => client.v2(getActivity, { path: { id } }),
  }),
  define({
    name: "products",
    recordType: "product",
    record: zGetProductsItem,
    fields: Object.keys(zGetProductsItem.shape),
    pushdown: { list: true, get: false },
    page: (cursor, customFields) => (client) =>
      client.v2(getProducts, { query: listQuery(cursor, customFields) }),
    one: (id) => (client) => client.v2(getProduct, { path: { id } }),
  }),
];

/** Every live resource, in the order the manifest and `--help` will list them. */
export const LIVE_RESOURCES: readonly string[] = RESOURCES.map(
  (resource) => resource.name,
);

const BY_NAME = new Map(RESOURCES.map((resource) => [resource.name, resource]));

/**
 * ADR-0009 §5: no aliases and no synonyms, so this is an exact-match lookup and
 * `people` simply is not a resource.
 */
export const resourceNamed = (name: string): Resource | undefined =>
  BY_NAME.get(name);
